AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
    TSYS Mock API

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
    Function:
        Timeout: 10


Resources:

    TSYSMockApiFunction:
        Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
        Properties:
            Handler: index.handler
            Runtime: nodejs8.10
            Policies: AWSLambdaBasicExecutionRole
            Environment: # More info about Env Vars: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#environment-object
                Variables:
                    PARAM1: VALUE
            Events:
                TSYSMockApi:
                    Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
                    Properties:
                        Path: /{proxy+}
                        Method: ANY

Outputs:
    TSYSMockApi:
      Description: "API Gateway endpoint URL for Prod stage for TSYS Mock API"
      Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/tsys/{proxy+}/"

    TSYSMockApiFunction:
      Description: "TSYS Mock Api Lambda Function ARN"
      Value: !GetAtt TSYSMockApiFunction.Arn

    TSYSMockApiFunctionIamRole:
      Description: "Implicit IAM Role created for TSYS Mock Api Function"
      Value: !GetAtt TSYSMockApiFunctionRole.Arn
